In [19]:
from sklearn.datasets import load_boston,
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
boston = load_boston()
df = pd.DataFrame(boston.data,columns = boston.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
y = boston.target

In [10]:

X_train,X_test,y_train,y_test = train_test_split(df, y, test_size = 0.3)
print(X_train.shape, y_train.shape)
print(X_test.shape,y_test.shape)

(354, 13) (354,)
(152, 13) (152,)


In [30]:
model = SVR()
model.fit(X_train,y_train)
out = model.predict(X_test)
score = model.score(X_test,y_test)
print(score)
print(mean_absolute_error(y_test,out))
print(mean_squared_error(y_test,out))
reg = RandomForestRegressor()
reg.fit(X_train,y_train)
res = reg.predict(X_test)
print(reg.score(X_test,y_test))
print(mean_absolute_error(y_test,res))
print(mean_squared_error(y_test,res))
model.fit_status_
print(model.support_vectors_)
print(model.dual_coef_)

-0.02486406213011128
6.776930965266541
92.11807465266732
0.8574333338590168
2.422894736842105
12.81435
0
[[6.4170e-02 0.0000e+00 5.9600e+00 ... 1.9200e+01 3.9690e+02 9.6800e+00]
 [8.1870e-02 0.0000e+00 2.8900e+00 ... 1.8000e+01 3.9353e+02 3.5700e+00]
 [4.6840e-02 0.0000e+00 3.4100e+00 ... 1.7800e+01 3.9218e+02 8.8100e+00]
 ...
 [2.8990e-02 4.0000e+01 1.2500e+00 ... 1.9700e+01 3.8985e+02 5.8900e+00]
 [4.1130e-02 2.5000e+01 4.8600e+00 ... 1.9000e+01 3.9690e+02 5.2900e+00]
 [7.8960e-02 0.0000e+00 1.2830e+01 ... 1.8700e+01 3.9492e+02 6.7800e+00]]
[[-1.          1.          1.          1.         -1.          1.
   1.         -1.         -1.          0.23856026  0.6388932  -1.
   1.         -0.86083603  1.         -1.         -1.          1.
  -1.          1.          1.          1.          1.          1.
  -0.36110488  1.         -1.          0.30864409 -1.          1.
  -1.         -1.         -1.         -1.          0.83800461 -1.
   1.          1.          0.93902035  0.54049106 -0.08